bin: replace echo with printf everywhere

diff --git a/bin/xdg-open b/bin/xdg-open
--- a/bin/xdg-open
+++ b/bin/xdg-open
@@ -5,10 +5,10 @@
 ###
 file="$1"
 
-[[ -z "$file" ]] && { echo 'argument required' >&2; exit 1; }
+[[ -z "$file" ]] && { printf "argument required\n" >&2; exit 1; }
 
 if [[ $file =~ ^magnet: ]] && [[ "$file" =~ xt=urn:btih:([^&/]+) ]]; then
-  echo "d10:magnet-uri${#file}:${file}e" > "$HOME/Downloads/meta-${BASH_REMATCH[1]}.torrent"
+  printf "d10:magnet-uri${#file}:${file}e\n" > "$HOME/Downloads/meta-${BASH_REMATCH[1]}.torrent"
   exit 0
 fi
 
@@ -18,7 +18,7 @@ if [[ ! -f "$file" ]]; then
 fi
 
 if ! which xdg-mime &>/dev/null; then
-  echo 'xdg-mime required' >&2
+  printf "xdg-mime required\n" >&2
   exit 1
 fi
 
@@ -34,7 +34,7 @@ read -r mimetype < \
     image/*)         mirage  "$file"  ;;
     text/*)          urxvtc -e vim "$file" ;;
     *)
-      echo "$file: unmatched mimetype, $mimetype" >&2
+      printf "%s: unmatched mimetype, %s\n" "$file" "$mimetype" >&2
       exit 1
       ;;
   esac
