Add AUR inventory script and data

diff --git a/hooks/post-up b/hooks/post-up
--- a/hooks/post-up
+++ b/hooks/post-up
@@ -1,4 +1,8 @@
 #!/bin/sh
+if ! aurtoi setup; then
+  echo "Unable to setup AUR inventory" >&2
+fi
+
 if [ -f ~/.netrc.gpg ]; then
   chmod 0600 ~/.netrc.gpg
 fi
